version: '3'

services:

  memsql:
    image: "memsql/cluster-in-a-box"
    ports:
      - 3306:3306
      - 8080:8080
    environment:
      LICENSE_KEY: ${LICENSE_KEY}
      START_AFTER_INIT: "Y"
      ROOT_PASSWORD: "password_here"
    volumes:
      - ./files:/mnt/data
    depends_on:
      - schema-registry

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    # disable logging for chatty container:
    logging:
      driver: none

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "actor:4:1"

  schema-registry:
    image: confluentinc/cp-schema-registry:5.4.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: localhost
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
